name: 🛠 Build and Deploy MARIA Dashboard

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
          path: build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
